"""Deterministic demo-seeding script (dashboard groundwork) — NOT the eval corpus.

Creates (or re-creates) a small curated set of demo cases in a DEDICATED demo
database (default <project>/data/demo.db) through the EXISTING machinery: the
real ORM models, the real agent loop (app.agent), the deterministic policy
engine, the SeededSandbox provider, and the hash-chained audit log.

    python -m scripts.seed_demo [--db-url sqlite:///...]

The 63-case evaluation corpus (app/eval/corpus.py) is untouched. The demo
cases deliberately span the behaviours a dashboard walkthrough needs:

    DEMO-INV-001  docs/GST blocker   -> AI (NLU) reads the email, documentation_fix
                                        playbook is authorized, invoice recovers.
    DEMO-INV-002  AP approval queue  -> AI reads "queued in AP", SUPERVISED mode
                                        parks the action; a human approves it in
                                        the audit trail; invoice recovers on the
                                        payer's stated date.
    DEMO-INV-003  explicit promise   -> AI extracts "15 January 2026", promise is
                                        confirmed + persisted; pays on that date.
    DEMO-INV-004  invoice dispute    -> escalate INVOICE_DISPUTE; no auto-collection.
    DEMO-INV-005  AVS fraud signal   -> deterministic fraud hard-stop; the AI and
                                        customer message cannot unlock a retry.
    DEMO-INV-006  DNC on file        -> deterministic compliance hard-stop.
    DEMO-INV-007  exactly 120 days   -> allowed by the compliance boundary -> recovers.
    DEMO-INV-008  121 days overdue   -> compliance-age hard-stop despite a paying
                                        profile (the rule beats the money).
    DEMO-INV-009  AP release + human  -> parked SUPERVISED and deliberately left
                                        PENDING_APPROVAL so the dashboard Approvals
                                        queue has a live item; Approve/Decline goes
                                        through the real decide_approval() mechanism.

Why this is honest, not theatrical:
  * Ground truth is what the payer's own message literally states.
  * The sandbox pays ONLY when the actually-executed intervention matches the
    seeded situation (profile docs_issue pays on resend_corrected_invoice, the
    ap_queue world on request_ap_update, ptp_offer_will_pay on confirm_ptp, and
    never_pays/flagged worlds never pay) — nothing reads the diagnosis or the
    "AI's reasoning".
  * Fraud / DNC / bankruptcy / >120-day outcomes are produced by deterministic
    policy rules in app/policy/rules.py, never by an LLM.
  * Every recovery and every stop is a real Diagnosis / Intervention / Approval
    / Escalation / AuditEvent row generated by the normal agent loop, all under
    a fixed virtual clock so re-runs are bit-identical.

Idempotency: the script DROPs and re-CREATEs the demo database schema on every
run, so running it twice never duplicates rows and always rebuilds the same
history. Everything in the demo DB is generated state — never source.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import constants as C  # noqa: E402
from app.agent import AgentConfig, decide_approval, run_tick  # noqa: E402
from app.audit import verify  # noqa: E402
from app.clock import VirtualClock, reset_clock, set_clock  # noqa: E402
from app.config import DATA_DIR  # noqa: E402
from app.db import init_db, make_engine, make_session  # noqa: E402
from app.eval.harness import seed_case, simulate_case  # noqa: E402
from app.execution.sandbox import SeededSandbox  # noqa: E402
from app.models import (  # noqa: E402
    Approval,
    CaseMessage,
    Customer,
    Escalation,
    Intervention,
    Invoice,
    RiskCase,
)
from sqlalchemy import select  # noqa: E402

DEFAULT_DB_URL = f"sqlite:///{DATA_DIR / 'demo.db'}"
T0 = datetime(2026, 1, 5, 10, 0, 0)  # Monday 10:00 IST — deterministic demo "now"


def _money(inr: int) -> int:
    return inr * 100  # paise (minor units), like the whole codebase


def _demo_case(
    seq: int,
    scenario: str,
    org: str,
    amount_inr: int,
    profile: str,
    *,
    flags: list[str] | None = None,
    due_days_ago: int = 0,
    attempts: list[tuple[str, int, str, str]] | None = None,
    messages: list[dict] | None = None,
    world_offset_hours: float | None = None,
    detection: str = "overdue_tick",
    gt_playbook: str,
    expected_inr: int = 0,
    should_escalate: bool = False,
) -> dict:
    """A demo case in the same shape the eval harness already understands."""
    inv_id = f"DEMO-INV-{seq:03d}"
    return {
        "id": f"demo_{seq:03d}",
        "scenario": scenario,
        "org": org,
        "invoice_id": inv_id,
        "amount_minor": _money(amount_inr),
        "paid_minor": 0,
        "currency": "INR",
        "profile": profile,
        "flags": flags or [],
        "due_days_ago": due_days_ago,
        "attempts": attempts or [],
        "promise_days": None,
        "future_events": [],
        "messages": [
            {
                "direction": "in",
                "channel": m.get("channel", "email"),
                "content": m["content"].replace("$INV", inv_id),
                "days_ago": float(m.get("days_ago", 2.0)),
            }
            for m in (messages or [])
        ],
        "world_offset_hours": world_offset_hours,
        "start_hour": 10,
        "detection": detection,
        "ground_truth": {
            "playbook": gt_playbook,
            "expected_recovery_minor": _money(expected_inr),
            "should_escalate": should_escalate,
        },
    }


# --------------------------------------------------------------------------- #
# Demo cases (see module docstring for the narrative of each)
# --------------------------------------------------------------------------- #
DEMO_CASES: list[dict] = [
    # 1. CLEAN AI RECOVERY — payer willing but blocked on a wrong GSTIN.
    _demo_case(
        1, "docs_gst_correction", "Meridian Auto Components", 420_000, "docs_issue",
        due_days_ago=35, world_offset_hours=52.0,
        messages=[{
            "days_ago": 4,
            "content": (
                "Good morning — this is the AP desk at Meridian Auto Components. "
                "Our finance team has approved invoice $INV, but the GSTIN printed "
                "on it is our old registration number. Please resend $INV with the "
                "corrected GSTIN and we will release the full payment within two "
                "working days of receiving the corrected copy."
            ),
        }],
        gt_playbook=C.PB_DOCUMENTATION_FIX, expected_inr=420_000,
    ),
    # 2. AP APPROVAL — payment approved internally + queued; SUPERVISED approval.
    _demo_case(
        2, "ap_approval_supervised", "Lakshmi Textile Mills", 275_000, "ap_queue",
        due_days_ago=38, world_offset_hours=240.0,  # payer's stated run: Thu 15 Jan
        messages=[{
            "days_ago": 2,
            "content": (
                "Hi — accounts payable at Lakshmi Textile Mills here. Invoice $INV "
                "has been approved by our purchase team and is queued for our finance "
                "payment run next Thursday. There is no need to escalate — we will "
                "release the payment on schedule. Please direct any questions to our "
                "AP inbox."
            ),
        }],
        gt_playbook=C.PB_AP_COORDINATION, expected_inr=275_000,
    ),
    # 3. PROMISE-TO-PAY — explicit date in the message; agent confirms and waits.
    _demo_case(
        3, "ptp_explicit_promise", "Surya Pharma Labs", 330_000, "ptp_offer_will_pay",
        due_days_ago=30,
        messages=[{
            "days_ago": 3,
            "content": (
                "Dear billing team — this is Surya Pharma Labs. We will transfer the "
                "full amount for invoice $INV on 15 January 2026 through our corporate "
                "banking portal. Please confirm this payment schedule and hold any "
                "collection reminders until that date."
            ),
        }],
        gt_playbook=C.PB_PROMISE_ACCEPT, expected_inr=330_000,
    ),
    # 4. INVOICE DISPUTE — escalate to a human; never auto-collect.
    _demo_case(
        4, "invoice_dispute", "Eastern Logistics Pvt Ltd", 245_000, "never_pays",
        due_days_ago=29,
        messages=[{
            "days_ago": 6,
            "content": (
                "This is Eastern Logistics. We did not receive the warehousing services "
                "billed on invoice $INV and we dispute the charges. Please investigate "
                "with your operations team — we will not pay anything until this "
                "dispute is closed."
            ),
        }],
        gt_playbook=C.PB_ESCALATE, should_escalate=True,
    ),
    # 5. FRAUD HARD-STOP — AVS mismatch + customer note; deterministic block wins.
    _demo_case(
        5, "fraud_avs_hardstop", "BlueOrbit Electronics", 160_000, "default",
        attempts=[("AVS_FAILED", 0, "AVS check failed — billing address mismatch", "card")],
        detection="webhook",
        messages=[{
            "days_ago": 0.2,
            "content": (
                "Important — someone attempted to use our corporate card on your "
                "payment page for invoice $INV without authorization. We have reported "
                "this to our bank and do not want that card retried."
            ),
        }],
        gt_playbook=C.PB_ESCALATE, should_escalate=True,
    ),
    # 6. DNC / COMPLIANCE STOP — do-not-contact on file; message reinforces it.
    _demo_case(
        6, "dnc_hardstop", "Kanha Agro Exports", 120_000, "never_pays",
        flags=[C.FLAG_DNC], due_days_ago=44,
        messages=[{
            "days_ago": 2,
            "content": (
                "Formal request: Kanha Agro Exports has asked to be removed from your "
                "billing contact lists. Please do not email, call, or send payment "
                "links about invoice $INV again."
            ),
        }],
        gt_playbook=C.PB_DUNNING, should_escalate=True,
    ),
    # 7. 120-DAY BOUNDARY — exactly at the limit: reminder still allowed, recovers.
    _demo_case(
        7, "120_day_boundary_allowed", "Vrishni Constructions", 145_000, "pays_after_reminder",
        due_days_ago=120,
        gt_playbook=C.PB_DUNNING, expected_inr=145_000,
    ),
    # 8. 121-DAY BOUNDARY — one day past the limit: hard-stop despite a paying profile.
    _demo_case(
        8, "121_day_boundary_blocked", "Tara Infra Projects", 170_000, "pays_after_reminder",
        due_days_ago=121,
        gt_playbook=C.PB_DUNNING, should_escalate=True,
    ),
    # 9. SUPERVISED + PENDING — parked for a human on purpose. The dashboard
    #    Approvals queue uses it to demonstrate the real decide_approval() flow
    #    (APPROVE settles the simulated payer instantly, DECLINE closes the case
    #    as CLOSED_NOOP). The driver below pins the sandbox settlement offset to
    #    0 so the live demo resolves within seconds of a human decision.
    _demo_case(
        9, "ap_release_today_supervised_pending", "Pinnacle FMCG Distributors", 190_000, "ap_queue",
        due_days_ago=33,
        messages=[{
            "days_ago": 1,
            "content": (
                "Hi — accounts payable at Pinnacle FMCG Distributors. Our finance "
                "team has approved invoice $INV and the treasurer will release the "
                "payment today. Please confirm our bank details on file are unchanged "
                "so the transfer goes through without delay."
            ),
        }],
        gt_playbook=C.PB_AP_COORDINATION, expected_inr=190_000,
    ),
]

SUPERVISED_SCENARIO = "ap_approval_supervised"  # runs through the human-approval driver
SUPERVISED_PENDING_SCENARIO = "ap_release_today_supervised_pending"  # parked for the dashboard


def _cfg_auto() -> AgentConfig:
    return AgentConfig(
        label="receivablesai-demo",
        mode=C.MODE_AUTONOMOUS,
        llm_mode="auto",
        offline_llm=True,  # deterministic NLU stand-in (no API key needed)
        provider=SeededSandbox(),
    )


def _cfg_supervised() -> AgentConfig:
    return AgentConfig(
        label="receivablesai-demo",
        mode=C.MODE_SUPERVISED,
        llm_mode="auto",
        offline_llm=True,
        provider=SeededSandbox(),
    )


# --------------------------------------------------------------------------- #
# Seeding drivers
# --------------------------------------------------------------------------- #
def run_autonomous(db, cc: dict, horizon_days: int = 45) -> None:
    """Replay the real agent loop until the case settles (eval-harness driver,
    same code path the 63-case evaluation uses; the sandbox pays only when the
    executed intervention matches the seeded scenario)."""
    simulate_case(db, cc, _cfg_auto(), horizon_days=horizon_days)


def run_supervised_approval(db, cc: dict) -> None:
    """SUPERVISED demo: park the action for a human, approve it in the audit
    trail, then let the simulated payer settle on their stated date."""
    clock = VirtualClock(start=T0)
    set_clock(clock)

    seed_case(db, cc, T0)
    db.commit()

    # tick -> overdue invoice opens a case -> diagnosis -> action parked
    run_tick(db, _cfg_supervised())
    db.commit()

    case = db.scalar(select(RiskCase).where(RiskCase.case_key == f"invoice:{cc['invoice_id']}"))
    assert case is not None, f"supervised case {cc['invoice_id']} was not opened"
    pending = db.scalars(
        select(Intervention).where(
            Intervention.case_id == case.id, Intervention.status == "PENDING_APPROVAL"
        )
    ).all()
    assert len(pending) == 1, f"expected exactly one parked action, got {len(pending)}"

    res = decide_approval(
        db,
        pending[0].id,
        decision="APPROVED",
        actor="finance-lead@receivablesai.demo",
        reason="Payer confirms invoice approved + queued in AP; light status follow-up authorized",
        cfg=_cfg_supervised(),
    )
    assert res["ok"], f"approval failed: {res}"
    db.commit()

    # advance to the moment the payer's simulated funds arrive, then drain
    inter = db.get(Intervention, pending[0].id)
    due = (inter.outcome or {}).get("pending_payment", {}).get("pending_at")
    assert due, f"approved action produced no simulated payment for {cc['invoice_id']}"
    clock.advance(to=datetime.fromisoformat(due) + timedelta(minutes=1))
    run_tick(db, _cfg_supervised())
    db.commit()


def run_supervised_pending(db, cc: dict) -> None:
    """SUPERVISED demo: park the action for a human and STOP.

    The case stays PENDING_APPROVAL in the demo DB so the dashboard Approvals
    queue has a live item; the human decision happens later through
    decide_approval() (APPROVE -> executor runs the parked action; DECLINE ->
    audited close). The simulated payer's settlement offset is pinned to 0 so
    an APPROVE resolves the case immediately after the decision.
    """
    clock = VirtualClock(start=T0)
    set_clock(clock)

    seed_case(db, cc, T0)
    db.commit()
    run_tick(db, _cfg_supervised())
    db.commit()

    case = db.scalar(select(RiskCase).where(RiskCase.case_key == f"invoice:{cc['invoice_id']}"))
    assert case is not None, f"supervised-pending case {cc['invoice_id']} was not opened"
    pending = db.scalars(
        select(Intervention).where(
            Intervention.case_id == case.id, Intervention.status == "PENDING_APPROVAL"
        )
    ).all()
    assert len(pending) == 1, f"expected exactly one parked action, got {len(pending)}"

    # deterministic world: the payer settles the moment the approved AP-status
    # follow-up executes (offset 0), so the live dashboard approval resolves.
    invoice = db.get(Invoice, case.invoice_id)
    meta = dict(invoice.meta or {})
    meta["scenario_offset_hours"] = 0.0
    invoice.meta = meta
    db.commit()


# --------------------------------------------------------------------------- #
# Post-seed annotation + report
# --------------------------------------------------------------------------- #
def _tag_demo_rows(db) -> None:
    """Mark every demo row as demo/simulated so the dashboard can filter and
    the sandbox origin of outcomes is explicit (honesty marker)."""
    invoice_ids = [
        inv.id for inv in db.scalars(select(Invoice)).all()
        if inv.rzr_invoice_id.startswith("DEMO-INV-")
    ]
    for inv in db.scalars(select(Invoice)).all():
        if inv.id in invoice_ids:
            meta = dict(inv.meta or {})
            meta.update({"demo": True, "simulated": True})
            inv.meta = meta
    for cust in db.scalars(select(Customer)).all():
        meta = dict(cust.meta or {})
        if cust.id in {inv.customer_id for inv in db.scalars(select(Invoice)).all() if inv.id in invoice_ids}:
            meta.update({"demo": True})
            cust.meta = meta
    for msg in db.scalars(select(CaseMessage)).all():
        if msg.invoice_id in invoice_ids:
            meta = dict(msg.meta or {})
            meta["demo"] = True
            msg.meta = meta


def _fmt(inr_paise: int) -> str:
    return f"Rs.{inr_paise / 100:,.0f}"


def _report(db) -> None:
    cases = db.scalars(select(RiskCase).order_by(RiskCase.id)).all()
    print(
        f"\n{'case':<14}{'scenario':<28}{'state':<20}{'cause:path':<26}{'recovered':<16}actions"
    )
    total_recovered = 0
    for case in cases:
        invoice = db.get(Invoice, case.invoice_id)
        scenario = ((invoice.meta or {}).get("eval_scenario")) or case.cause
        intervs = db.scalars(
            select(Intervention).where(Intervention.case_id == case.id).order_by(Intervention.id)
        ).all()
        acts = ", ".join(
            f"{i.playbook}/{i.action}:{i.status}" for i in intervs if i.status != "PENDING_APPROVAL"
        ) or "(none - hard stop / escalate)"
        recovered = case.recovered_amount_minor
        total_recovered += recovered
        print(
            f"{case.entity_id:<14}{scenario:<28}{case.state:<20}"
            f"{case.cause + ':' + case.diagnosis_path:<26}{_fmt(recovered):<16}{acts[:110]}"
        )

    blocked = [c for c in cases if c.state in (C.STATE_STOPPED_COMPLIANCE, C.STATE_STOPPED_FRAUD)]
    escalated = [c for c in cases if c.state == C.STATE_ESCALATED]
    recovered_cases = [c for c in cases if c.state == C.STATE_RECOVERED]
    approvals = db.scalars(select(Approval)).all()
    escal_rows = db.scalars(select(Escalation)).all()
    pending_acts = db.scalars(
        select(Intervention).where(Intervention.status == "PENDING_APPROVAL")
    ).all()
    ok, _broken, msg = verify(db)
    print(
        f"\nDemo summary - {len(cases)} cases | {len(recovered_cases)} recovered "
        f"({_fmt(total_recovered)}) | {len(blocked)} deterministic hard-stops | "
        f"{len(escalated)} escalated | {len(approvals)} human approval(s) | "
        f"{len(pending_acts)} pending approval(s) | "
        f"{len(escal_rows)} escalation row(s)"
    )
    print(f"Audit chain: {msg}")
    if not ok:
        raise SystemExit("audit chain verification FAILED after demo seed")


def main() -> None:
    parser = argparse.ArgumentParser(description="Recreate the ReceivablesAI demo database")
    parser.add_argument("--db-url", default=None, help="sqlite URL (default: data/demo.db)")
    args = parser.parse_args()
    db_url = args.db_url
    if not db_url:
        import os

        db_url = os.getenv("RA_DEMO_DB_URL", DEFAULT_DB_URL)

    print(f"Recreating demo database at {db_url}")
    engine = make_engine(db_url)
    from app.models import Base

    Base.metadata.drop_all(engine)  # idempotency: a fresh, duplicate-free history
    init_db(engine)
    db = make_session(engine)

    reset_clock()
    for cc in DEMO_CASES:
        set_clock(VirtualClock(start=T0))
        if cc["scenario"] == SUPERVISED_SCENARIO:
            run_supervised_approval(db, cc)
        elif cc["scenario"] == SUPERVISED_PENDING_SCENARIO:
            run_supervised_pending(db, cc)
        else:
            run_autonomous(db, cc)
        print(f"  seeded {cc['invoice_id']:<14} scenario={cc['scenario']}")

    reset_clock()
    _tag_demo_rows(db)
    db.commit()

    _report(db)
    db.close()


if __name__ == "__main__":
    main()
